@hostname = localhost
@port = 5000
@protocol = http
@host = {{hostname}}:{{port}}
@contentType = application/json

### test APIs with rest client extension


### register user
POST {{protocol}}://{{host}}/auth/register HTTP/1.1
content-type: {{contentType}}

{
    "registerType": "guest",
    "userName": "shubhamstr"
}
###


### login user
POST {{protocol}}://{{host}}/auth/login HTTP/1.1
content-type: {{contentType}}

{
    "loginType": "email",
    "email": "shubhamsutar5799@gmail.com",
    "password": "1234"
}
###