@hostname = localhost
@port = 5000
@protocol = http
@host = {{hostname}}:{{port}}
@contentType = application/json

### test APIs with rest client extension


### get all users
GET {{protocol}}://{{host}}/users/get-all HTTP/1.1
###

### register user
POST {{protocol}}://{{host}}/users/register HTTP/1.1
content-type: {{contentType}}

{
    "registerType": "guest",
    "userName": "shubhamstr"
}
###

### update user
POST {{protocol}}://{{host}}/users/update-notification HTTP/1.1
content-type: {{contentType}}

{
    "id": "1",
    "email_notification_flag": "1",
    "push_notification_flag": "1",
    "email_message_flag": "1",
    "push_message_flag": "1"
}
###

### update user
POST {{protocol}}://{{host}}/users/update-personal HTTP/1.1
content-type: {{contentType}}

{
    "id": "1",
    "last_name": "Sutar",
    "first_name": "Shubham",
    "username": "shubhamstr",
    "email": "shubhamsutar5799@gmail.com"
}
###

### update user
POST {{protocol}}://{{host}}/users/update-image HTTP/1.1
content-type: {{contentType}}

{
    "id": "1",
    "image": "user.png"
}
###

### update user
POST {{protocol}}://{{host}}/users/update-image HTTP/1.1
content-type: {{contentType}}

{
    "id": "1",
    "password": "1234"
}
###

### delete users
POST {{protocol}}://{{host}}/users/delete HTTP/1.1
content-type: {{contentType}}

{
    "id": "1"
}
###